# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Utku Kaynar
email: utkukaynar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writings of Utku Kaynar on Software, Art, Photography and Life in general.
  Articles in English and Turkish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://utkukaynar.com.tr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: utkukaynar
github_username:  utkukaynar
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compose
google_analytics: UA-64906345-2
author: Utku Kaynar
social:
  name: Utku Kaynar
  links:
    - https://twitter.com/utkukaynar
    - https://linkedin.com/in/utkukaynar
    - https://facebook.com/utku.kaynar
    - https://github.com/utkukaynar

disqus:
  shortname: utkukaynar

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      _author: "Utku Kaynar"
      image: 'assets/utku.jpg'
      comments: true
